### PR TITLE
Avoid drawing ERD if hidden, redraw on bootstrap tab refresh

### LINKED ISSUE #35: ERD component breaks when the svg are not present in the screen
In a discussion, the description isn't visible, so the SVG is not present and the components fails.
We shouldn't try to draw the lines if the SVG's aren't present. 
In labo, we'll need to trigger an event on tab change, to generate the re-render.

To reproduce this issue, go to a discussion for a SQL exercise.

### PR DESCRIPTION
**Pull request by Javi**
Fixes #35 (including labo)

### CODE REVIEW

File: src/javascripts/_er-diagram.js [hunk 1]
```diff
@@ -238,4 +241,8 @@ mumuki.load(function () {
     $('.mu-erd').renderERD();
   });
 
+  //Redraw on bootstrap tab change event
+  $('a[data-toggle="tab"]').on('shown.bs.tab', function () {
```
Comment (flbulgarelli) [inline src/javascripts/_er-diagram.js:245]: What if the tabs are not related with the ERD? Will this flick or produce any inappropriate behaviour?

**Review by flbulgarelli — CHANGES_REQUESTED** [review]

File: src/javascripts/_er-diagram.js (hunk 1 above)
Comment (Javi) [reply src/javascripts/_er-diagram.js:245]: I tested it out on tabs without any ERDs and it didn't seem to behave any differently, the function is a no-op if no proper SVG or ERD elements are found

**Review by flbulgarelli — APPROVED** [review]
